# experiment with makes ability to source a file from the current directory

# setup-env needs to be proceeded with a ./ or source cannot find it
# apprently when bash is in posix mode, it only searches PATH for
# files to source (see man bash)

all:
	. ./setup-env; echo ${CLIFF}

