######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 6 10:59:58 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += lcdrange.h
SOURCES += lcdrange.cpp main.cpp
