// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package packet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Index                int32                `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Duration             int32                `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Value                float32              `protobuf:"fixed32,4,opt,name=value,proto3" json:"value,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Event) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Event) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Event) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type Events struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Events) Reset()         { *m = Events{} }
func (m *Events) String() string { return proto.CompactTextString(m) }
func (*Events) ProtoMessage()    {}
func (*Events) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *Events) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Events.Unmarshal(m, b)
}
func (m *Events) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Events.Marshal(b, m, deterministic)
}
func (m *Events) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Events.Merge(m, src)
}
func (m *Events) XXX_Size() int {
	return xxx_messageInfo_Events.Size(m)
}
func (m *Events) XXX_DiscardUnknown() {
	xxx_messageInfo_Events.DiscardUnknown(m)
}

var xxx_messageInfo_Events proto.InternalMessageInfo

func (m *Events) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "packet.Event")
	proto.RegisterType((*Events)(nil), "packet.Events")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0x41, 0x6e, 0x85, 0x20,
	0x18, 0x84, 0x03, 0x0a, 0x69, 0x7f, 0xd3, 0x2e, 0x48, 0x17, 0xc4, 0x4d, 0x89, 0x49, 0x13, 0x56,
	0x98, 0xd8, 0x33, 0xf4, 0x02, 0xa4, 0x17, 0xc0, 0x42, 0x0d, 0xa9, 0x8a, 0x51, 0x34, 0xbd, 0x45,
	0xaf, 0xdc, 0x08, 0xcf, 0xb7, 0x1c, 0x66, 0x86, 0xff, 0x1b, 0xa8, 0xdc, 0xe1, 0xe6, 0xa8, 0x96,
	0x35, 0xc4, 0xc0, 0xe8, 0x62, 0xbe, 0x7e, 0x5c, 0xac, 0x5f, 0x87, 0x10, 0x86, 0xd1, 0xb5, 0xe9,
	0xb5, 0xdf, 0xbf, 0xdb, 0xe8, 0x27, 0xb7, 0x45, 0x33, 0x2d, 0x39, 0xd8, 0xfc, 0x21, 0x20, 0x1f,
	0x67, 0x91, 0x3d, 0x03, 0xf6, 0x96, 0x23, 0x81, 0xe4, 0xa3, 0xc6, 0xde, 0xb2, 0x17, 0x20, 0x7e,
	0xb6, 0xee, 0x97, 0x63, 0x81, 0x24, 0xd1, 0x59, 0xb0, 0x1a, 0x1e, 0xec, 0xbe, 0x9a, 0xe8, 0xc3,
	0xcc, 0x8b, 0x64, 0xdc, 0xf5, 0xd9, 0x38, 0xcc, 0xb8, 0x3b, 0x5e, 0x0a, 0x24, 0xb1, 0xce, 0x82,
	0x29, 0x28, 0xcf, 0xa3, 0x9c, 0x08, 0x24, 0xab, 0xae, 0x56, 0x99, 0x48, 0x5d, 0x44, 0xea, 0xf3,
	0x22, 0xd2, 0x29, 0xd7, 0xb4, 0x40, 0x13, 0xd0, 0xc6, 0xde, 0x80, 0xa6, 0x4d, 0x1b, 0x47, 0xa2,
	0x90, 0x55, 0xf7, 0xa4, 0xf2, 0x2a, 0x95, 0x7c, 0x7d, 0x33, 0x7b, 0x9a, 0xbe, 0x7a, 0xff, 0x0f,
	0x00, 0x00, 0xff, 0xff, 0x27, 0x20, 0xb7, 0x81, 0x01, 0x01, 0x00, 0x00,
}
