// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sample.proto

package packet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Sample_Type int32

const (
	Sample_ANALOG Sample_Type = 0
	Sample_DIGIO  Sample_Type = 1
)

var Sample_Type_name = map[int32]string{
	0: "ANALOG",
	1: "DIGIO",
}

var Sample_Type_value = map[string]int32{
	"ANALOG": 0,
	"DIGIO":  1,
}

func (x Sample_Type) String() string {
	return proto.EnumName(Sample_Type_name, int32(x))
}

func (Sample_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2141552de9bf11d0, []int{0, 0}
}

type Sample struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 Sample_Type          `protobuf:"varint,2,opt,name=type,proto3,enum=packet.Sample_Type" json:"type,omitempty"`
	Index                int32                `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Value                float32              `protobuf:"fixed32,4,opt,name=value,proto3" json:"value,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Sample) Reset()         { *m = Sample{} }
func (m *Sample) String() string { return proto.CompactTextString(m) }
func (*Sample) ProtoMessage()    {}
func (*Sample) Descriptor() ([]byte, []int) {
	return fileDescriptor_2141552de9bf11d0, []int{0}
}

func (m *Sample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sample.Unmarshal(m, b)
}
func (m *Sample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sample.Marshal(b, m, deterministic)
}
func (m *Sample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sample.Merge(m, src)
}
func (m *Sample) XXX_Size() int {
	return xxx_messageInfo_Sample.Size(m)
}
func (m *Sample) XXX_DiscardUnknown() {
	xxx_messageInfo_Sample.DiscardUnknown(m)
}

var xxx_messageInfo_Sample proto.InternalMessageInfo

func (m *Sample) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Sample) GetType() Sample_Type {
	if m != nil {
		return m.Type
	}
	return Sample_ANALOG
}

func (m *Sample) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Sample) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Sample) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type Samples struct {
	Samples              []*Sample `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Samples) Reset()         { *m = Samples{} }
func (m *Samples) String() string { return proto.CompactTextString(m) }
func (*Samples) ProtoMessage()    {}
func (*Samples) Descriptor() ([]byte, []int) {
	return fileDescriptor_2141552de9bf11d0, []int{1}
}

func (m *Samples) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Samples.Unmarshal(m, b)
}
func (m *Samples) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Samples.Marshal(b, m, deterministic)
}
func (m *Samples) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Samples.Merge(m, src)
}
func (m *Samples) XXX_Size() int {
	return xxx_messageInfo_Samples.Size(m)
}
func (m *Samples) XXX_DiscardUnknown() {
	xxx_messageInfo_Samples.DiscardUnknown(m)
}

var xxx_messageInfo_Samples proto.InternalMessageInfo

func (m *Samples) GetSamples() []*Sample {
	if m != nil {
		return m.Samples
	}
	return nil
}

func init() {
	proto.RegisterEnum("packet.Sample_Type", Sample_Type_name, Sample_Type_value)
	proto.RegisterType((*Sample)(nil), "packet.Sample")
	proto.RegisterType((*Samples)(nil), "packet.Samples")
}

func init() { proto.RegisterFile("sample.proto", fileDescriptor_2141552de9bf11d0) }

var fileDescriptor_2141552de9bf11d0 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0x3d, 0x5d, 0xdb, 0xb1, 0x33, 0x29, 0x23, 0x7a, 0x11, 0x06, 0x62, 0xe8, 0x8d, 0xb9,
	0xca, 0xa0, 0x7b, 0x82, 0x81, 0x30, 0x06, 0xe2, 0x20, 0xee, 0x05, 0x3a, 0x7b, 0x1c, 0xc5, 0xd6,
	0x06, 0x9b, 0x89, 0x7b, 0x37, 0x1f, 0x4e, 0x9a, 0x43, 0x2f, 0x76, 0xf9, 0xff, 0xf9, 0x92, 0xff,
	0x23, 0x78, 0xdb, 0x97, 0xad, 0x6b, 0xc8, 0xb8, 0xef, 0xce, 0x77, 0x22, 0x75, 0xe5, 0xfb, 0x27,
	0xf9, 0xe5, 0xe3, 0xa9, 0xeb, 0x4e, 0x0d, 0xad, 0x42, 0x7b, 0x3c, 0x7f, 0xac, 0x7c, 0xdd, 0x52,
	0xef, 0xcb, 0xd6, 0x31, 0x98, 0xff, 0x01, 0xa6, 0x6f, 0xe1, 0xa6, 0xc8, 0x30, 0xaa, 0x2b, 0x09,
	0x0a, 0xf4, 0xcc, 0x46, 0x75, 0x25, 0x9e, 0x30, 0xf6, 0x17, 0x47, 0x32, 0x52, 0xa0, 0xb3, 0xe2,
	0xce, 0xf0, 0x93, 0x86, 0x69, 0x73, 0xb8, 0x38, 0xb2, 0x01, 0x10, 0xf7, 0x98, 0xd4, 0x5f, 0x15,
	0xfd, 0xca, 0x89, 0x02, 0x9d, 0x58, 0x0e, 0x43, 0xfb, 0x53, 0x36, 0x67, 0x92, 0xb1, 0x02, 0x1d,
	0x59, 0x0e, 0xc2, 0x60, 0x3c, 0x28, 0xc8, 0x44, 0x81, 0x9e, 0x17, 0x4b, 0xc3, 0x7e, 0x66, 0xf4,
	0x33, 0x87, 0xd1, 0xcf, 0x06, 0x2e, 0x7f, 0xc0, 0x78, 0x58, 0x12, 0x88, 0xe9, 0xe6, 0x75, 0xf3,
	0xb2, 0xdf, 0x2e, 0x6e, 0xc4, 0x0c, 0x93, 0xe7, 0xdd, 0x76, 0xb7, 0x5f, 0x40, 0xbe, 0xc6, 0x29,
	0xfb, 0xf4, 0x42, 0xe3, 0x94, 0xbf, 0xa0, 0x97, 0xa0, 0x26, 0x7a, 0x5e, 0x64, 0xd7, 0xc6, 0x76,
	0x3c, 0x3e, 0xa6, 0x61, 0x6d, 0xfd, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x70, 0xd8, 0x37, 0xa1, 0x33,
	0x01, 0x00, 0x00,
}
