
all: test.c
#	gcc `pkg-config --cflags --libs glib-2.0` -o glib-gspawn-async-test test.c
	source setup-env; arm-angstrom-linux-gnueabi-gcc `pkg-config --cflags --libs glib-2.0` -o glib-gspawn-async-test test.c

